# Generated by Django 5.2.4 on 2025-08-04 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0002_alter_address_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a short title of your offer.', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('rooms', models.IntegerField(verbose_name='Number of rooms')),
                ('real_estate_type', models.CharField(help_text='Apartment, House, Studio, Hotel, Hostel, B&Bs, etc.', max_length=150, verbose_name='Type of Real estate.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is offer active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='addresses.address', verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='users.userprofile', verbose_name='Owner of an offer - Landlord')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
