# Generated by Django 5.2.4 on 2025-08-07 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_options'),
        ('offers', '0002_alter_offer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='offer',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='addresses.address', verbose_name='Address'),
        ),
    ]
