# Generated by Django 5.2.4 on 2025-08-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.CharField(blank=True, max_length=10, null=True)),
                ('building', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
            ],
        ),
    ]
